/*
    @author     cleancoda
    @date       10112023
    @detail     drops existing base sql objects generated by app
    @log
                cc  10112023 - generated basic script file
*/

-- drop tables in order of constraint keys (if exist)
go

-- add checks and feature to backup objects labeled Notiflyer_backup_
