/*
    @author     cleancoda
    @date       11172023
    @detail     drops existing base sql objects generated by app
    @log
                cc  11172023 - generated basic script file
*/

-- drop if temp table exists
if object_id('tempdb..#notiflyer_tbTempTable') is not null
    drop table #notiflyer_tbTempTable;
go

-- store in temp table to loop through
select
    [object_id]
    ,[name]
    ,[type]
    ,row_number() over (order by object_id) as [rowid]
into 
    #notiflyer_tbTempTable
from
    sys.objects
where   
    -- filter on notiflyer labeled table objects
    name like 'notiflyer_sp%'
    -- ignore any backup objects if exist
    and name not like '%_backup_%'
order by 
    [type];

-- variables for loop/cmd
declare
    @rowcounter as int = 0
    ,@loopcounter as int = 0
    ,@objectname as nvarchar(max) = ''
    ,@objecttype as nvarchar(max) = ''
    ,@dropcmd as nvarchar(max) = ''
    ,@sqlcmd as nvarchar(max) = '';

-- store number of objects to be dropped
select
    @rowcounter = coalesce(max([rowid]),count(1))
from
    #notiflyer_tbTempTable;

-- loop through objects
while(@loopcounter <= @rowcounter)
    begin
        -- prep sql statement to drop object
        select
            @sqlcmd = 
                        'drop ' 
                        + 
                            case [type]
                                when 'P' then 'procedure '
                            end
                        + name
            ,@objectname = [name]
            ,@objecttype = [type]
        from
            #notiflyer_tbTempTable
        where   
            rowid = @loopcounter;
        
        -- exec cmd if objects found
        if @@rowcount > 0
        begin try
            print 'dropping object: ' + @objectname;
            exec(@sqlcmd);
        end try
        begin catch
            print 'error occurred while attempting to drop ' + @objectname;
            select
                error_message(), error_line(), error_number(), error_severity(), error_state();
        end catch

        -- next object
        select
            @loopcounter += 1;
    end

-- print # of objects dropped (reduce 1 for array starting index)
print try_cast(@loopcounter - 1 as nvarchar(max)) + ' objects successfully dropped';
