if object_id('notiflyer_spGetMetaData') is not null
    print 'notiflyer_spGetMetaData stored procedure exists, skipping create attempt..'
    print 'ignore error below, cannot create exception handling on ddl statements'
    return;
go

create procedure notiflyer_spGetMetaData
/*
    @author     cleancoda
    @date       11112023
    @detail     procedure to accept several parameters, including sql queries to 
                generate and return a table as output containing metadata about the query
                passed as a parameter
    @sample
                exec notiflyer_spGetMetaData
                    @query_select = 'select *'
                    ,@query_from = 'from Sales.Customers' ;
    @log
                cc  11112023 - generated basic script file
*/
(
    @query_select as nvarchar(max) = ''
    ,@query_from as nvarchar(max) = ''
    ,@query_where as nvarchar(max) = ''
    ,@query_groupby as nvarchar(max) = ''
    ,@column_legend nvarchar(max) = ''
    ,@column_x nvarchar(max) = ''
    ,@column_y nvarchar(max) = ''
    ,@returnvalue int = 0 output
    ,@returnmessage nvarchar(255) = '' output
)
as
begin
    begin try
        -- if no query passed end routine
        if(@query_select = '' or @query_from = '')
            begin
                return;
            end

        -- variables
        declare
            @query as nvarchar(max);

        -- build local query
        select
            @query = @query_select + ' ' + @query_from + ' ' + @query_where + ' ' + @query_groupby;

        -- clear tempdb
        if object_id('tempdb..#tmpNotiflyer_tbMetaDataColumns') is not null 
        drop table #tmpNotiflyer_tbMetaDataColumns;

        -- setup temp table to hold metadata columns generated by sp_describe_first_result_set
        create table #tmpNotiflyer_tbMetaDataColumns
        (
            is_hidden bit not null,
            column_ordinal int not null,
            name sysname null,
            is_nullable bit not null,
            system_type_id int not null,
            system_type_name nvarchar(256) null,
            max_length smallint not null,
            precision tinyint not null,
            scale tinyint not null,
            collation_name sysname null,
            user_type_id int null,
            user_type_database sysname null,
            user_type_schema sysname null,
            user_type_name sysname null,
            assembly_qualified_type_name nvarchar(4000),
            xml_collection_id int null,
            xml_collection_database sysname null,
            xml_collection_schema sysname null,
            xml_collection_name sysname null,
            is_xml_document bit not null,
            is_case_sensitive bit not null,
            is_fixed_length_clr_type bit not null,
            source_server sysname null,
            source_database sysname null,
            source_schema sysname null,
            source_table sysname null,
            source_column sysname null,
            is_identity_column bit null,
            is_part_of_unique_key bit null,
            is_updateable bit null,
            is_computed_column bit null,
            is_sparse_column_set bit null,
            ordinal_in_order_by_list smallint null,
            order_by_list_length smallint null,
            order_by_is_descending smallint null,
            tds_type_id int not null,
            tds_length int not null,
            tds_collation_id int null,
            tds_collation_sort_id tinyint null
        );

        -- insert results of query metadata columns into new temp table
        insert #tmpNotiflyer_tbMetaDataColumns
        exec sp_describe_first_result_set 
                @tsql = @query, 
                @params = null, 
                @browse_information_mode = 0;

        -- return metadata columns
        select
            column_ordinal as id
            ,name
            ,system_type_name as data_type
            ,max_length
            ,precision
            ,scale
        from
            #tmpNotiflyer_tbMetaDataColumns;

    end try

    begin catch
        select
            error_line() as 'error_line'
            ,error_number() as 'error_number'
            ,error_severity() as 'error_severity'
            ,error_message() as 'error_message'
            ,error_procedure() as 'error_procedure'
            ,error_state() as 'error_state';
    end catch    
end
go 
