if object_id('notiflyer_spGetAPIPayload') is not null
    print 'notiflyer_spGetAPIPayload stored procedure exists, skipping create attempt..'
    print 'ignore error below, cannot create exception handling on ddl statements'
    return;
go

create procedure notiflyer_spGetAPIPayload
/*
    @author     cleancoda
    @date       11162023
    @detail     future feature set for notiflyer - currently setup as default placeholder
                accepts rest api parameters for performing get,post,delete operations on the api
    @sample
                exec notiflyer_spGetAPIPayload
                    @api_url = 'https://reqres.in/api/users?page=2'
                    ,@api_payload_type = 'application/json'
                    ,@api_method = 'GET'
                    ,@api_key = NULL
                    ,@api_bodydata_type = NULL
    @log
                cc  11162023 - generated basic script file
*/
(

    @api_url varchar(8000) = ''                             -- api endpoint url
    ,@api_payload_type nvarchar(255) = 'application/json'   -- application/json, application/xml
    ,@api_method nvarchar(5) = 'GET'                        -- GET, POST, PUT, DELETE
    ,@api_key varchar(8000) = NULL                          -- authorization key, api key, bearer key
    ,@api_bodydata_type nvarchar(255) = NULL                -- json string - parse using key/value pair definition '{"key":"value"}'
)
as 
begin
    begin try

    /*
        ------------------------------------------------------------
        prerequisites
        ------------------------------------------------------------
        in order for the following procedure to work, the target server must 
        have 'ole automation procedures' system configuration property enabled

        note: sql servers hosted on linux do not support ole automation routines
        doc: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2022

        =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        script to enable sp_OA methods:
        =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
            exec sp_configure 'show advanced options', 1;
            go
            reconfigure;
            go

            sp_configure 'Ole Automation Procedures', 1;
            go
            reconfigure;
            go

        ------------------------------------------------------------
        procedure logic
        ------------------------------------------------------------
        mssql provides access to http services via WinHttp 
        utilize WinHttp objects for making api calls from t-sql

        ------------------------------------------------------------
        relevant objects documentation
        ------------------------------------------------------------
        WinHttp object -
        - https://learn.microsoft.com/en-us/windows/win32/winhttp/winhttp-start-page
        - https://learn.microsoft.com/en-us/windows/win32/winhttp/about-winhttp

        WinHttpRequest object -
        - https://learn.microsoft.com/en-us/windows/win32/winhttp/winhttprequest

        ------------------------------------------------------------
        workflow:
        ------------------------------------------------------------
            1.  init WinHttp object using version 5.1
            2.  open a new http connection using sp_OAMethod and pass url at time of init
            3.  init object depending on whether api requests auth code or switch header 
                content type from json to xml update the WinHttp object using sp_OAMethod calls
            4.  send request to api endpoint using iwinhttprequest-send
            5.  store response/error and return to calling code

    */

    -- p

    -- global vars
    declare
        @WinHttpRequest as int                      -- object token address generated by WinHttp object at time of init
        ,@WinHttpRequestReturnCode as int           -- rc for instantiating @WinHttpRequest
        ,@WinHttpOpenConnectionReturnCode as int    -- rc for instantiating httpconnection object and connecting to api endpoint
        ,@HttpAuthReturnCode as int                 -- rc for applying API key
        ,@HttpContentTypeReturnCode as int          -- rc for applying content type spec
        ,@HttpRequestReturnCode as int              -- rc for http request delivery
        ,@HttpResponseReturnCode as int             -- rc for final http reponse

        -- prepare winhttp object
        begin try
            -- initialize WinHttp.WinHttpRequest object
            -- doc: https://learn.microsoft.com/en-us/windows/win32/winhttp/winhttp-versions
            -- note: 5.0 has been deprecated - https://learn.microsoft.com/en-us/windows/win32/winhttp/winhttp-versions#version-50
            exec 
                @WinHttpRequestReturnCode = sp_OACreate 'WinHttp.WinHttpRequest.5.1', @WinHttpRequest out;

            -- if init routine returned an error, go to error_block
            if @WinHttpRequestReturnCode <> 0 goto error_block
        end try
        begin catch
            -- handle exceptions while initializing WinHttp.WinHttpRequest object
            select
                error_line() as 'error_line'
                ,error_number() as 'error_number'
                ,error_severity() as 'error_severity'
                ,error_message() as 'error_message'
                ,error_procedure() as 'error_procedure'
                ,error_state() as 'error_state'

            -- exit routine
            return;
        end catch

        -- prepare and exec http request
        begin try
            if @WinHttpRequestReturnCode = 0
            begin
                -- init http connection object and connect to api end-point
                -- pass @WinHttpRequest object to http connection
                -- run sync call and perform http request and pass api url
                exec 
                    @WinHttpOpenConnectionReturnCode = sp_OAMethod @WinHttpRequest, 'Open', NULL, @api_method, @api_url, 'false'

                -- if init routine returned an error, go to error_block
                if @WinHttpOpenConnectionReturnCode <> 0 goto error_block

                -- include authorization api key if applicable
                if @api_key is not null
                begin
                    exec @HttpAuthReturnCode = sp_OAMethod @WinHttpRequest, 'SetRequestHeader', NULL, 'Authorization', @api_key;
                    -- if auth request routine returned an error, go to error_block
                    if @HttpAuthReturnCode <> 0 goto error_block
                end

                -- change payload content type if applicable by overriding routine parameter at runtime
                if @api_payload_type is not null
                begin
                    exec @HttpContentTypeReturnCode = sp_OAMethod @WinHttpRequest, 'SetRequestHeader', NULL, 'Content-Type', @api_payload_type;
                    -- if content type set request routine returned an error, go to error_block
                    if @HttpContentTypeReturnCode <> 0 goto error_block
                end

                -- request ready and waiting on send to api
                -- https://learn.microsoft.com/en-us/windows/win32/winhttp/iwinhttprequest-send
                
                -- check if additional json metadata is supplied for payload
                if @api_bodydata_type is not null
                begin
                    exec @HttpRequestReturnCode = sp_OAMethod @WinHttpRequest, 'Send', NULL, @api_bodydata_type;
                    -- if http request routine returned an error, go to error_block
                    if @HttpRequestReturnCode <> 0 goto error_block
                end
                else
                begin
                    exec @HttpRequestReturnCode = sp_OAMethod @WinHttpRequest, 'Send';
                    -- if http request routine returned an error, go to error_block
                    if @HttpRequestReturnCode <> 0 goto error_block
                end
            end
        end try
        begin catch
            -- handle exceptions while initializing WinHttp.WinHttpRequest object
            select
                error_line() as 'error_line'
                ,error_number() as 'error_number'
                ,error_severity() as 'error_severity'
                ,error_message() as 'error_message'
                ,error_procedure() as 'error_procedure'
                ,error_state() as 'error_state'

            -- exit routine
            return;
        end catch

        -- get response from http request
        begin try
            -- temp table variable to hold http request response
            declare 
                @response as table
                (
                    ResponseText nvarchar(max)
                );

            -- execute request and store response in temp table
            insert into @response
            exec @HttpResponseReturnCode = sp_OAGetProperty @WinHttpRequest, 'ResponseText';
            -- if http response routine returned an error, go to error_block
            if @HttpResponseReturnCode <> 0 goto error_block

            -- return json parsed string
            select
                ResponseText
            from
                @response;

            -- end routine and return to calling code
            return;
            
        end try
        begin catch
        end catch

    -- exception handling for http requests/responses
    error_block:
        begin
            -- capture error log using sp_OAGetErrorInfo
            -- doc: https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-oageterrorinfo-transact-sql

            -- temp table variable to hold error results
            declare
                @error_log as table
                (
                    Error binary(4)
                    ,Source varchar(8000)
                    ,Description varchar(8000)
                    ,HelpFile varchar(8000)
                    ,HelpID varchar(8000)
                );
            
            -- insert error values
            insert into @error_log
            exec sp_OAGetErrorInfo @WinHttpRequest;

            -- parse results to json (if replying back as a json response, comment above select)
            select
                    ( 
						select *
						from
                            @error_log
						for
                            json auto
					) as ResponseText;
        end

        -- garbage collection & cleanup
        -- doc: https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-oadestroy-transact-sql
        if @WinHttpRequest is not null
            exec sp_OADestroy @WinHttpRequest;

    end try
    begin catch
        -- handle global exceptions
        select
            error_line() as 'error_line'
            ,error_number() as 'error_number'
            ,error_severity() as 'error_severity'
            ,error_message() as 'error_message'
            ,error_procedure() as 'error_procedure'
            ,error_state() as 'error_state'

        -- exit routine
        return;
    end catch
end