if object_id('notiflyer_spGetAPIPayload') is not null
    print 'notiflyer_spGetAPIPayload stored procedure exists, skipping create attempt..'
    print 'ignore error below, cannot create exception handling on ddl statements'
    return;
go

create procedure notiflyer_spGetAPIPayload
/*
    @author     cleancoda
    @date       11162023
    @detail     future feature set for notiflyer - currently setup as default placeholder
                accepts rest api parameters for performing get,post,delete operations on the api
    @log
                cc  11162023 - generated basic script file
*/
(

    @api_url nvarchar(8000) = ''            -- api endpoint url
    ,@api_method nvarchar(5) = ''           -- GET, POST, PUT, DELETE
    ,@api_key nvarchar(8000) = ''           -- authorization key, api key, bearer key
    ,@api_payload_type nvarchar(255) = ''   -- application/json, application/xml
    ,@api_bodydata_type nvarchar(255) = ''  -- json string - parse using key/value pair definition '{"key":"value"}'
)
as 
begin
    begin try

    /*
        ------------------------------
        procedure logic
        ------------------------------
        mssql provides access to http services via WinHttp 
        utilize WinHttp objects for making api calls from t-sql

        ------------------------------
        relevant documentation:
        ------------------------------
        WinHttp object -
        - https://learn.microsoft.com/en-us/windows/win32/winhttp/winhttp-start-page
        - https://learn.microsoft.com/en-us/windows/win32/winhttp/about-winhttp

        WinHttpRequest object -
        - https://learn.microsoft.com/en-us/windows/win32/winhttp/winhttprequest

        workflow:
            1.  init WinHttp object using version 5.1
            2.  open a new http connection using sp_OAMethod and pass url at time of init
            3.  init depending on whether api requests auth code or switch header content type from json to xml
                update the WinHttp object using sp_OAMethod calls
        
        
            4.  send request to api endpoint using iwinhttprequest-send

    */

    -- global vars
    declare
        @WinHttpRequest as int                  -- object token address generated by WinHttp object at time of init
        ,@WinHttpRequestReturnCode as int;      -- rc for instantiating @WinHttpRequest

        begin try
            
            -- declare and initialize WinHttp.WinHttpRequest object
            -- doc: https://learn.microsoft.com/en-us/windows/win32/winhttp/winhttp-versions

            -- init
            -- 5.0 has been deprecated - https://learn.microsoft.com/en-us/windows/win32/winhttp/winhttp-versions#version-50
        end try
        begin catch
        end catch


    end try
    begin catch
    end catch
end