/*
    @author     cleancoda
    @date       10112023
    @detail     drops existing base sql objects generated by app
    @log
                cc  10112023 - generated basic script file
*/

-- drop if temp table exists
if object_id('tempdb..#notiflyer_tbTempTable') is not null
    drop table #notiflyer_tbTempTable;
go

-- store in temp table to loop through
select
    [object_id]
    ,[name]
    ,[type]
    ,row_number() over (order by object_id) as [rowid]
into 
    #notiflyer_tbTempTable
from
    sys.objects
where   
    -- filter on notiflyer labeled objects
    name like 'notiflyer%'
    -- ignore any backup objects if exist
    and name not like '%_backup_%'
order by 
    [type];

-- variables for loop/cmd
declare
    @rowcounter as int = 0
    ,@loopcounter as int = 0
    ,@objectname as nvarchar(max)
    ,@objecttype as nvarchar(max)
    ,@dropcmd as nvarchar(max)
    ,@sqlcmd as nvarchar(max);

-- store number of objects to be dropped
select
    @rowcounter = coalesce(max([rowid]),count(1))
from
    #notiflyer_tbTempTable;

-- loop through objects
while(@loopcounter <= @rowcounter)
    begin
        
        -- prep sql statement to drop object
        select
            @sqlcmd = 
                        'drop ' 
                        + 
                            case [type]
                                when 'U' then 'table '
                                when 'V' then 'view '
                                when 'P' then 'procedure '
                                when 'FN' then 'function '
                            end
                        + name
            ,@objectname = [name]
            ,@objecttype = [type]
        from
            #notiflyer_tbTempTable
        where   
            rowid = @loopcounter;

        -- if object type is a table, check for constraints
        -- existing constraints need to be dropped before dropping host table
        if(@objecttype = 'U')
        begin
            -- prep ddl command
            select
                @dropcmd += 'alter table ' + quotename(cs.name) + '.' + quotename(ct.name) 
                            + ' drop constraint ' + quotename(fk.name) + ';'
            from sys.foreign_keys as fk
            inner join sys.tables as ct on 
                fk.parent_object_id = ct.[object_id]
                inner join sys.schemas as cs on
                    ct.[schema_id] = cs.[schema_id]
            where
                ct.name = @objectname;

            -- drop constraints
            print @dropcmd;
            exec(@dropcmd);
        end
        
        -- exec cmd
        exec(@sqlcmd);

        -- next object
        select
            @loopcounter += 1;
    end
